language: node_js

matrix:
  include:
  - node_js: v10.0.0
    env:
    - NO_LINT=1
  - node_js: v14.6.0

script:
- npm run clean
- if [ "$NO_LINT" != "1" ]; then npm run lint; fi
- npm run build
- npm run test
